analytics:
  ua: ''
  gtag: ''
  gtm: ''
  ga_prod: ''
breadcrumbs:
  goal:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  indicator:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  post:
    - path: /
      label: general.home
    - path: /news
      label: menu.updates
cookie_consent_form:
  enabled: false
country:
  name: general.pais
  adjective: general.adjetivo
create_goals:
  layout: goal-with-progress
  previous_next_links: false
  goals: []
create_indicators:
  previous_next_links: false
create_pages:
  - filename: ''
    folder: /goals
    layout: goals
    title: general.goals
  - filename: ''
    folder: /reporting-status
    layout: reportingstatus
    title: status.reporting_status
  - filename: ''
    folder: /search
    layout: search
    title: search.search
custom_css: []
custom_js:
  - /assets/js/custom.js
data_edit_url: data
data_fields:
  units: Unidad
  series: Serie
date_formats: 
  - type: standard
    language: en
    format: '%B %d, %Y'
  - type: standard
    language: es
    format: '%d de %B de %Y'
  - type: standard
    language: eu
    format: '%Y %B %d'
disclaimer:
  phase: ''
  message: ''
  hidden: false
email_contacts:
  questions: test@example.com
  suggestions: test@example.com
  functional: test@example.com
environment: staging
footer_language_toggle: none
footer_menu:
frontpage_cards:
  - title: frontpage.download_all
    content: ''
    include: components/download-all-data.html
    button_label: ''
    button_link: ''
    rule_color: ''
  - title: Lorem ipsum
    content: |
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi mollis
      cursus est sed dapibus.
    include: ''
    button_label: Read more
    button_link: 'https://example.com'
    rule_color: ''
  - title: Nam vestibulum
    content: |
      Nam vestibulum, purus quis porttitor imperdiet, nisl sem mollis nisl, a
      interdum risus enim vitae tortor. Donec feugiat accumsan rutrum.
    include: ''
    button_label: Read more
    button_link: 'https://example.com'
    rule_color: ''
frontpage_goals_grid:
  title: frontpage.heading_short
  description: frontpage.instructions_shorter
frontpage_introduction_banner:
goal_image_base: 'https://eustat-des.github.io/site/assets/img/goals'
goal_image_extension: ''
goals_page:
  title: general.goals
  description: frontpage.instructions_shorter
graph_color_headline: '#004466'
graph_color_headline_high_contrast: '#55a6e5'
graph_color_set: accessible
graph_color_list: []
graph_color_number: 0
graph_title_from_series: false
header_language_toggle: links
hide_empty_metadata: true
hide_single_series: true
hide_single_unit: true
indicator_config_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/indicator-config
  translation_link: ''
indicator_data_form:
  enabled: true
  repository_link: /tree/develop/data
indicator_metadata_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/meta
  translation_link: ''
  language: ''
  scopes:
    - national
    - global
  exclude_fields: []
  translated: true
indicator_tabs:
  tab_1: ''
  tab_2: ''
  tab_3: ''
  tab_4: ''
languages:
  - es
  - eu
  - en
languages_public: []
logos: 
  - language: es
    src: assets/img/SDG_logo.png
    alt: Ir a la página de inicio
  - language: eu
    src: assets/img/eu/SDG_logo.png
    alt: Joan hasierako orrira
  - language: en
    src: assets/img/en/SDG_logo.png
    alt: Go to homepage
map_layers:
  - subfolder: Territorio
    label: Territorio
    min_zoom: 1
    max_zoom: 4
    staticBorders: true
  - subfolder: Comarca
    label: Comarca
    min_zoom: 5
    max_zoom: 6
    staticBorders: true
  - subfolder: Municipio
    label: Municipio
    min_zoom: 7
    max_zoom: 11
    staticBorders: true
map_options:
  disaggregation_controls: true
  minZoom: 1
  maxZoom: 11
  tileURL: ''
  tileOptions:
    id: ''
    accessToken: ''
    attribution: ''
  colorRange: chroma.brewer.BuGn
  noValueColor: '#f0f0f0'
  styleNormal:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#888888'
    dashArray: ''
  styleHighlighted:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#111111'
    dashArray: ''
  styleStatic:
    weight: 2
    opacity: 1
    fillOpacity: 0
    color: '#172d44'
    dashArray: ''
menu:
  - path: /
    translation_key: general.home
    dropdown: []
  - path: /goals
    translation_key: general.goals
    dropdown: []
  - path: /reporting-status
    translation_key: menu.reporting_status
    dropdown: []
  - path: /news
    translation_key: menu.updates
    dropdown: []
  - path: /faq
    translation_key: menu.faq
    dropdown: []  
  - path: /about
    translation_key: menu.about
    dropdown: []    
metadata_edit_url: metadata
metadata_tabs:
  - scope: national
    title: indicator.national_metadata
    description: indicator.national_metadata_blurb
  - scope: global
    title: indicator.global_metadata
    description: indicator.global_metadata_blurb
  - scope: sources_alt
    title: indicator.sources
    description: ''
news:
  category_links: false
progress_status:
  status_heading: status.progress_status
  status_help: status.progress_status
  status_types:
    - value: not_available
      label: status.progress_not_available
      image: assets/img/progress/not-available.png
      alt: status.progress_not_available
      hide_on_goal_pages: false
    - value: target_achieved
      label: status.progress_target_achieved
      image: assets/img/progress/target-achieved.png
      alt: status.progress_target_achieved
      hide_on_goal_pages: false
    - value: challenges_remain
      label: status.progress_challenges_remain
      image: assets/img/progress/challenges-remain.png
      alt: status.progress_challenges_remain
      hide_on_goal_pages: false
    - value: approaching_target
      label: status.progress_approaching_target
      image: assets/img/progress/approaching-target.png
      alt: status.progress_approaching_target
      hide_on_goal_pages: false
remote_data_prefix: 'https://eustat-des.github.io/data/'
reporting_status:
  title: status.reporting_status
  description: status.description
  disaggregation_tabs: true
  status_types:
    - value: complete
      label: status.reported_online
      hide_on_goal_pages: false
    - value: notstarted
      label: status.no_data_available
      hide_on_goal_pages: false
    - value: notapplicable
      label: status.not_applicable
      hide_on_goal_pages: false
repository_url_data: 'https://github.com/EUSTAT-DES/data'
repository_url_site: 'https://github.com/EUSTAT-DES/site'
search_index_boost: []
search_index_extra_fields: []
site_config_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/_data
  translation_link: ''
time_series_attributes:
  - field: COMMENT_TS
    label: indicator.footnote
  - field: DATA_LAST_UPDATE
    label: metadata_fields.national_data_update_url
use_new_config_forms: true
validate_indicator_config: false
validate_site_config: false
x_axis_label: ''
