analytics:
  ua: ''
  gtag: ''
  gtm: ''
  ga_prod: ''
breadcrumbs:
  goal:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  indicator:
    - path: /
      label: general.home
  post:
    - path: /
      label: general.home
    - path: /news
      label: menu.updates
cookie_consent_form:
  enabled: false
country:
  name: general.pais
  adjective: general.adjetivo
create_goals:
  layout: goal-with-progress
  previous_next_links: true
  goals: []    
create_indicators:
  previous_next_links: true
create_pages:
  - filename: ''
    folder: /goals
    layout: goals
    title: general.goals
  - filename: ''
    folder: /jarraipen-txostena
    layout: progrestatus
    title: status.reporting_status
  - filename: ''
    folder: /search
    layout: search
    title: search.search
custom_css: []
custom_js:
  - /assets/js/custom.js
data_edit_url: data
data_fields:
  units: Units
  series: Series
date_formats: 
  - type: standard
    language: en
    format: '%Y/%m/%d'
  - type: standard
    language: es
    format: '%d/%m/%Y'
  - type: standard
    language: eu
    format: "%Y/%m/%d"
desagregacion_territorial_keyword:
  eu: "Lurralde historikoa"
  es: "Territorio histórico"
  en: "Province"
desagregacion_municipio_keyword: 
  eu: "Udalerria"
  es: "Municipio"
  en: "Municipality"
desagregacion_sexo_keyword: 
  eu: "Sexua"
  es: "Sexo"
  en: "Sex"
disclaimer:
  phase: ''
  message: ''
  hidden: false
email_contacts:
  questions: test@example.com
  suggestions: test@example.com
  functional: test@example.com
environment: staging
footer_language_toggle: none
footer_menu:
frontpage_cards:
  - title: frontpage.download_all
    content: ''
    include: components/download-all-data.html
    button_label: ''
    button_link: ''
    rule_color: ''
  - title: frontpage.publicaciones
    content: frontpage.publicaciones_content
    rule_color: ''
  - title: frontpage.recursosUtiles
    content: frontpage.recursosUtiles_content
    rule_color: ''
frontpage_goals_grid:
  title: frontpage.heading_short
  description: frontpage.instructions_shorter
frontpage_introduction_banner:
goal_image_base: 'https://eustat-des.github.io/site/assets/img/goals'
goal_image_extension: ''
goals_page:
  title: general.goals
  description: frontpage.instructions_shorter
graph_color_headline: ['#e5243b', '#dda63a', '#4c9f38', '#c5192d', '#ff3a21', '#26bde2', '#fcc30b', '#a21942', '#fd6925', '#dd1367', '#fd9d24', '#bf8b2e', '#3f7e44', '#0a97d9', '#56c02b', '#00689d', '#19486a']
graph_color_headline_high_contrast: '#55a6e5'
graph_color_set: 'goal'
graph_color_list: []
graph_color_number: 9
graph_title_from_series: true
header_language_toggle: links
hide_empty_metadata: true
hide_single_series: true
hide_single_unit: true
indicator_config_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/indicator-config
  translation_link: ''
indicator_data_form:
  enabled: true
  repository_link: /tree/develop/data
indicator_metadata_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/meta
  translation_link: ''
  language: ''
  scopes:
    - national
    - global
  exclude_fields: []
  translated: true
indicator_tabs:
  tab_1: ''
  tab_2: ''
  tab_3: ''
  tab_4: ''
languages:
  - eu
  - es
  - en
languages_public: []
logos: 
  - language: es
    src: assets/img/logo/SDG_logo_es.png
    alt: Ir a la página de inicio
  - language: eu
    src: assets/img/logo/SDG_logo_eu.png
    alt: Joan hasierako orrira
  - language: en
    src: assets/img/logo/SDG_logo_en.png
    alt: Go to homepage
map_layers:
  - subfolder: Territorio
    label: indicator.territorio
    min_zoom: 5
    max_zoom: 6
    staticBorders: true
  - subfolder: Comarca
    label: indicator.comarca
    min_zoom: 7
    max_zoom: 8
    staticBorders: true
  - subfolder: Municipio
    label: indicator.municipio
    min_zoom: 9
    max_zoom: 14
    staticBorders: true
map_options:
  disaggregation_controls: true
  minZoom: 5
  maxZoom: 14
  tileURL: 'https://www.geo.euskadi.eus/geoeuskadi/rest/services/U11/WMTS_GRIS/MapServer/WMTS/tile/1.0.0/U11_WMTS_GRIS/default/default028mm/{z}/{y}/{x}.png'
  tileOptions:
    id: ''
    accessToken: ''
    attribution: <a href="https://www.geo.euskadi.eus/" title="Eusko Jaurlaritza/Gobierno Vasco - geoEuskadi">geoEuskadi</a>
  colorRange: [["#FCE9EB", "#F7BDC4", "#F2929D", "#ED6676", "#E83A4F", "#E5243B", "#B71D2F", "#891623", "#5C0E18", "#2E070C"],
              ["#FCF8EB", "#F7E9C2", "#F2DB9A", "#EDCD72", "#E8BE49", "#E5B735", "#CEA530", "#A08025", "#735C1B", "#453710"],
              ["#EDF5EB", "#C9E2C3", "#A6CF9C", "#82BC74", "#5EA94C", "#4C9F38", "#3D7F2D", "#2E5F22", "#1E4016", "#0F200B"],
              ["#F9E8EA", "#EEBAC0", "#E28C96", "#D65E6C", "#CB3042", "#C5192D", "#9E1424", "#760F1B", "#4F0A12", "#270509"],
              ["#FFEBE9", "#FFC4BC", "#FF9D90", "#FF7564", "#FF4E37", "#FF3A21", "#CC2E1A", "#992314", "#66170D", "#330C07"],
              ["#E9F8FB", "#BEEBF6", "#93DEF0", "#67D1EA", "#3CC4E5", "#26BDE2", "#1E97B5", "#177188", "#0F4C5A", "#08262D"],
              ["#FFF9E7", "#FEEDB6", "#FEE185", "#FDD554", "#FCC923", "#FCC30B", "#CA9C09", "#977507", "#654E04", "#322702"],
              ["#F6E8EC", "#E3BAC6", "#D18CA1", "#BE5E7B", "#AB3055", "#A21942", "#821435", "#610F28", "#410A1A", "#20050D"],
              ["#FFF0E9", "#FED2BE", "#FEB492", "#FE9666", "#FD783B", "#FD6925", "#CA541E", "#983F16", "#652A0F", "#331507"],
              ["#FCE7F0", "#F5B8D1", "#EE89B3", "#E75A95", "#E02B76", "#DD1367", "#B10F52", "#850B3E", "#580829", "#2C0415"],
              ["#FFF5E6", "#FEE2B3", "#FECE80", "#FEBA4D", "#FDA71A", "#FD9D00", "#CA7E00", "#985E00", "#653F00", "#331F00"],
              ["#FAF5EA", "#EFE0C0", "#E4CC96", "#D9B86C", "#CEA342", "#C9992D", "#A17A24", "#795C1B", "#503D12", "#281F09"],
              ["#ECF2EC", "#C5D8C7", "#9FBFA2", "#79A57C", "#528B57", "#3F7E44", "#326536", "#264C29", "#19321B", "#0D190E"],
              ["#E7F5FB", "#B6E0F4", "#85CBEC", "#54B6E4", "#23A1DD", "#0A97D9", "#0879AE", "#065B82", "#043C57", "#021E2B"],
              ["#EEF9EA", "#CCECBF", "#ABE095", "#89D36B", "#67C640", "#56C02B", "#459A22", "#34731A", "#224D11", "#112609"],
              ["#E6F0F5", "#B3D2E2", "#80B4CE", "#4D95BA", "#1A77A7", "#00689D", "#00537E", "#003E5E", "#002A3F", "#00151F"],
              ["#E8EDF0", "#BAC8D2", "#8CA4B5", "#5E7F97", "#305A79", "#19486A", "#143A55", "#0F2B40", "#0A1D2A", "#050E15"]]
  noValueColor: '#f0f0f0'
  styleNormal:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#888888'
    dashArray: ''
  styleHighlighted:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#111111'
    dashArray: ''
  styleStatic:
    weight: 2
    opacity: 1
    fillOpacity: 0
    color: '#172d44'
    dashArray: ''
menu:
  - path: /
    translation_key: general.home
    dropdown: []
  - path: /jarraipen-txostena
    translation_key: menu.reporting_status
    dropdown: []
  - translation_key: menu.desagregaciones
    dropdown:
      - path: /lurraldea/
        translation_key: menu.territorio
      - path: /udalerria/
        translation_key: menu.municipal
      - path: /sexua/
        translation_key: menu.sexo   
  - translation_key: menu.masInfo
    dropdown: 
      - path: /agenda2030/
        translation_key: menu.agenda2030
      - path: /aurkezpena/
        translation_key: menu.indicadores
      - path: /plataforma/
        translation_key: menu.acercaDe   
metadata_edit_url: metadata
metadata_tabs:
  - scope: national
    title: indicator.national_metadata
    description: indicator.national_metadata_blurb
  - scope: sources_alt
    title: indicator.sources
    description: ''
  - scope: global
    title: indicator.global_metadata
    description: indicator.global_metadata_blurb
news:
  category_links: false
observation_attributes:
  - field: COMMENT_OBS
    label: indicator.footnote
progress_status:
  status_heading: status.progress_status
  status_help: status.progress_status
  status_types:
    - value: alcanzado
      label: status.alcanzado
      image: assets/img/progress/alcanzado.png
      alt: status.alcanzado
      hide_on_goal_pages: false
    - value: progreso
      label: status.en_progreso
      image: assets/img/progress/en_progreso.png
      alt: status.en_progreso
      hide_on_goal_pages: false
    - value: retroceso
      label: status.retroceso
      image: assets/img/progress/retroceso.png
      alt: status.retroceso
      hide_on_goal_pages: false
    - value: noevaluado
      label: status.no_evaluado
      image: assets/img/progress/no_evaluado.png
      alt: status.no_evaluado
      hide_on_goal_pages: false
    - value: notstarted
      label: status.no_data_available
      image: assets/img/progress/notstarted.png
      alt: status.no_data_available
      hide_on_goal_pages: false
    - value: notapplicable
      label: status.not_applicable
      hide_on_goal_pages: false
remote_data_prefix: 'https://eustat-des.github.io/data/'
reporting_status:
  title: status.reporting_status
  description: status.description
  disaggregation_tabs: false
  status_types:
    - value: notstarted
      label: status.no_data_available
      hide_on_goal_pages: false
    - value: complete
      label: status.reported_online
      hide_on_goal_pages: true
    - value: notapplicable
      label: status.not_applicable
      hide_on_goal_pages: false
repository_url_data: 'https://github.com/EUSTAT-DES/data'
repository_url_site: 'https://github.com/EUSTAT-DES/site'
search_index_boost: []
search_index_extra_fields: []
site_config_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/_data
  translation_link: ''
time_series_attributes:
  - field: COMMENT_TS
    label: indicator.footnote
  - field: DATA_LAST_UPDATE
    label: metadata_fields.national_data_update_url
use_new_config_forms: true
